# Generated by Django 3.2.7 on 2021-12-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0007_auto_20211214_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
